export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAIL = "QUESTION_FAIL";

export const TEST_REQUEST = "TEST_REQUEST";
export const TEST_SUCCESS = "TEST_SUCCESS";
export const TEST_FAIL = "TEST_FAIL";

export const USER_GETALLQUESTIONS_REQUEST =
    "USER_GETALLQUESTIONS_REQUEST";
export const USER_GETALLQUESTIONS_SUCCESS =
    "USER_GETALLQUESTIONS_SUCCESS";
export const USER_GETALLQUESTIONS_FAIL =
    "USER_GETALLQUESTIONS_FAIL";

export const GET_QUESTION_BYID_REQUEST =
    "GET_QUESTION_BYID_REQUEST";
export const GET_QUESTION_BYID_SUCCESS =
    "GET_QUESTION_BYID_SUCCESS";
export const GET_QUESTION_BYID_FAIL =
    "GET_QUESTION_BYID_FAIL";
