export const QUESTION_REQUEST = 'QUESTION_REQUEST'
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS'
export const QUESTION_FAIL = 'QUESTION_FAIL'

export const OPTION_REQUEST = 'OPTION_REQUEST'
export const OPTION_SUCCESS = 'OPTION_SUCCESS'
export const OPTION_FAIL = 'OPTION_FAIL'

export const TEST_REQUEST = 'TEST_REQUEST'
export const TEST_SUCCESS = 'TEST_SUCCESS'
export const TEST_FAIL = 'TEST_FAIL'

