export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";
export const QUESTION_FAIL = "QUESTION_FAIL";

export const SCORE_REQUEST = "SCORE_REQUEST";
export const SCORE_SUCCESS = "SCORE_SUCCESS";
export const SCORE_FAIL = "SCORE_FAIL";

// export const DELETE_QUESTION_BYID_REQUEST =
//     "DELETE_QUESTION_BYID_REQUEST";
// export const DELETE_QUESTION_BYID_SUCCESS =
//     "DELETE_QUESTION_BYID_SUCCESS";
// export const DELETE_QUESTION_BYID_FAIL =
//     "DELETE_QUESTION_BYID_FAIL";
