export const USER_REGISTRATION_REQUEST =
    "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS =
    "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL =
    "USER_REGISTRATION_FAIL";
export const USER_REGISTRATION_RESET =
    "USER_REGISTRATION_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_VIEWADMIN_REQUEST =
    "USER_VIEWADMIN_REQUEST";
export const USER_VIEWADMIN_SUCCESS =
    "USER_VIEWADMIN_SUCCESS";
export const USER_VIEWADMIN_FAIL = "USER_VIEWADMIN_FAIL";

export const USER_SECTION_REQUEST = "USER_SECTION_REQUEST";
export const USER_SECTION_SUCCESS = "USER_SECTION_SUCCESS";
export const USER_SECTION_FAIL = "USER_SECTION_FAIL";

export const GETALLADMIN_REQUEST = "GETALLADMIN_REQUEST";
export const GETALLADMIN_SUCCESS = "GETALLADMIN_SUCCESS";
export const GETALLADMIN_FAIL = "GETALLADMIN_FAIL";

export const GETCANDIDATESDETAILS_REQUEST =
    "GETCANDIDATESDETAILS_REQUEST";
export const GETCANDIDATESDETAILS_SUCCESS =
    "GETCANDIDATESDETAILS_SUCCESS";
export const GETCANDIDATESDETAILS_FAIL =
    "GETCANDIDATESDETAILS_FAIL";
